server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: people-counter
    static_configs:
      - targets:
          - localhost
        labels:
          job: people_counter
          __path__: /var/log/events.log
    pipeline_stages:
      - json:
          expressions:
            type: type
      - labels:
          type: